/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-vercel-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  serial,
  varchar,
  boolean,
  timestamp,
  numeric,
  type AnyPgColumn,
  jsonb,
  pgEnum,
} from '@payloadcms/db-vercel-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-vercel-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'editor', 'user'])
export const enum_admin_invitations_role = pgEnum('enum_admin_invitations_role', [
  'admin',
  'editor',
  'user',
])
export const enum_sources_type = pgEnum('enum_sources_type', [
  'official_program',
  'speech',
  'interview',
  'press_release',
  'vote',
  'article',
  'report',
  'other',
])
export const enum_sources_verification_status = pgEnum('enum_sources_verification_status', [
  'pending',
  'verified',
  'disputed',
  'archived',
])
export const enum_sources_status = pgEnum('enum_sources_status', ['draft', 'published'])
export const enum__sources_v_version_type = pgEnum('enum__sources_v_version_type', [
  'official_program',
  'speech',
  'interview',
  'press_release',
  'vote',
  'article',
  'report',
  'other',
])
export const enum__sources_v_version_verification_status = pgEnum(
  'enum__sources_v_version_verification_status',
  ['pending', 'verified', 'disputed', 'archived'],
)
export const enum__sources_v_version_status = pgEnum('enum__sources_v_version_status', [
  'draft',
  'published',
])
export const enum_parties_status = pgEnum('enum_parties_status', ['draft', 'published'])
export const enum__parties_v_version_status = pgEnum('enum__parties_v_version_status', [
  'draft',
  'published',
])
export const enum_candidates_candidacy_status = pgEnum('enum_candidates_candidacy_status', [
  'declared',
  'expected',
  'exploring',
  'withdrawn',
  'not_candidate',
])
export const enum_candidates_status = pgEnum('enum_candidates_status', ['draft', 'published'])
export const enum__candidates_v_version_candidacy_status = pgEnum(
  'enum__candidates_v_version_candidacy_status',
  ['declared', 'expected', 'exploring', 'withdrawn', 'not_candidate'],
)
export const enum__candidates_v_version_status = pgEnum('enum__candidates_v_version_status', [
  'draft',
  'published',
])
export const enum_topics_status = pgEnum('enum_topics_status', ['draft', 'published'])
export const enum__topics_v_version_status = pgEnum('enum__topics_v_version_status', [
  'draft',
  'published',
])
export const enum_programs_status = pgEnum('enum_programs_status', ['draft', 'published'])
export const enum__programs_v_version_status = pgEnum('enum__programs_v_version_status', [
  'draft',
  'published',
])
export const enum_proposals_proposal_status = pgEnum('enum_proposals_proposal_status', [
  'announced',
  'confirmed',
  'changed',
  'withdrawn',
  'unclear',
])
export const enum_proposals_status = pgEnum('enum_proposals_status', ['draft', 'published'])
export const enum__proposals_v_version_proposal_status = pgEnum(
  'enum__proposals_v_version_proposal_status',
  ['announced', 'confirmed', 'changed', 'withdrawn', 'unclear'],
)
export const enum__proposals_v_version_status = pgEnum('enum__proposals_v_version_status', [
  'draft',
  'published',
])
export const enum_public_positions_position_type = pgEnum('enum_public_positions_position_type', [
  'speech',
  'interview',
  'vote',
  'social_post',
  'press_release',
  'debate',
  'other',
])
export const enum_public_positions_stance = pgEnum('enum_public_positions_stance', [
  'supports',
  'opposes',
  'mixed',
  'unclear',
  'not_applicable',
])
export const enum_public_positions_status = pgEnum('enum_public_positions_status', [
  'draft',
  'published',
])
export const enum__public_positions_v_version_position_type = pgEnum(
  'enum__public_positions_v_version_position_type',
  ['speech', 'interview', 'vote', 'social_post', 'press_release', 'debate', 'other'],
)
export const enum__public_positions_v_version_stance = pgEnum(
  'enum__public_positions_v_version_stance',
  ['supports', 'opposes', 'mixed', 'unclear', 'not_applicable'],
)
export const enum__public_positions_v_version_status = pgEnum(
  'enum__public_positions_v_version_status',
  ['draft', 'published'],
)

export const users_role = pgTable(
  'users_role',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_users_role('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('users_role_order_idx').on(columns.order),
    index('users_role_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [users.id],
      name: 'users_role_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    email: varchar('email').notNull(),
    emailVerified: boolean('email_verified').notNull().default(false),
    image: varchar('image'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    banned: boolean('banned').default(false),
    banReason: varchar('ban_reason'),
    banExpires: timestamp('ban_expires', { mode: 'string', withTimezone: true, precision: 3 }),
    twoFactorEnabled: boolean('two_factor_enabled').default(false),
  },
  (columns) => [
    uniqueIndex('users_email_idx').on(columns.email),
    index('users_created_at_idx').on(columns.createdAt),
    index('users_updated_at_idx').on(columns.updatedAt),
  ],
)

export const sessions = pgTable(
  'sessions',
  {
    id: serial('id').primaryKey(),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    token: varchar('token').notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    ipAddress: varchar('ip_address'),
    userAgent: varchar('user_agent'),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    impersonatedBy: integer('impersonated_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    uniqueIndex('sessions_token_idx').on(columns.token),
    index('sessions_created_at_idx').on(columns.createdAt),
    index('sessions_updated_at_idx').on(columns.updatedAt),
    index('sessions_user_idx').on(columns.user),
    index('sessions_impersonated_by_idx').on(columns.impersonatedBy),
  ],
)

export const accounts = pgTable(
  'accounts',
  {
    id: serial('id').primaryKey(),
    accountId: varchar('account_id').notNull(),
    providerId: varchar('provider_id').notNull(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    accessToken: varchar('access_token'),
    refreshToken: varchar('refresh_token'),
    idToken: varchar('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    scope: varchar('scope'),
    password: varchar('password'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('accounts_account_id_idx').on(columns.accountId),
    index('accounts_user_idx').on(columns.user),
    index('accounts_created_at_idx').on(columns.createdAt),
    index('accounts_updated_at_idx').on(columns.updatedAt),
  ],
)

export const verifications = pgTable(
  'verifications',
  {
    id: serial('id').primaryKey(),
    identifier: varchar('identifier').notNull(),
    value: varchar('value').notNull(),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('verifications_identifier_idx').on(columns.identifier),
    index('verifications_created_at_idx').on(columns.createdAt),
    index('verifications_updated_at_idx').on(columns.updatedAt),
  ],
)

export const two_factors = pgTable(
  'two_factors',
  {
    id: serial('id').primaryKey(),
    secret: varchar('secret').notNull(),
    backupCodes: varchar('backup_codes').notNull(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    verified: boolean('verified'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('two_factors_secret_idx').on(columns.secret),
    index('two_factors_user_idx').on(columns.user),
    index('two_factors_updated_at_idx').on(columns.updatedAt),
    index('two_factors_created_at_idx').on(columns.createdAt),
  ],
)

export const admin_invitations = pgTable(
  'admin_invitations',
  {
    id: serial('id').primaryKey(),
    role: enum_admin_invitations_role('role').notNull().default('admin'),
    token: varchar('token').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('admin_invitations_token_idx').on(columns.token),
    index('admin_invitations_updated_at_idx').on(columns.updatedAt),
    index('admin_invitations_created_at_idx').on(columns.createdAt),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const sources = pgTable(
  'sources',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    type: enum_sources_type('type').default('other'),
    url: varchar('url'),
    archivedUrl: varchar('archived_url'),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    publisher: varchar('publisher'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    retrievedAt: timestamp('retrieved_at', { mode: 'string', withTimezone: true, precision: 3 }),
    language: varchar('language').default('fr'),
    quote: varchar('quote'),
    notes: varchar('notes'),
    verificationStatus: enum_sources_verification_status('verification_status').default('pending'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_sources_status('_status').default('draft'),
  },
  (columns) => [
    index('sources_file_idx').on(columns.file),
    index('sources_published_at_idx').on(columns.publishedAt),
    index('sources_updated_at_idx').on(columns.updatedAt),
    index('sources_created_at_idx').on(columns.createdAt),
    index('sources__status_idx').on(columns._status),
  ],
)

export const _sources_v = pgTable(
  '_sources_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => sources.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_type: enum__sources_v_version_type('version_type').default('other'),
    version_url: varchar('version_url'),
    version_archivedUrl: varchar('version_archived_url'),
    version_file: integer('version_file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_publisher: varchar('version_publisher'),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_retrievedAt: timestamp('version_retrieved_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_language: varchar('version_language').default('fr'),
    version_quote: varchar('version_quote'),
    version_notes: varchar('version_notes'),
    version_verificationStatus: enum__sources_v_version_verification_status(
      'version_verification_status',
    ).default('pending'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__sources_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_sources_v_parent_idx').on(columns.parent),
    index('_sources_v_version_version_file_idx').on(columns.version_file),
    index('_sources_v_version_version_published_at_idx').on(columns.version_publishedAt),
    index('_sources_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_sources_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_sources_v_version_version__status_idx').on(columns.version__status),
    index('_sources_v_created_at_idx').on(columns.createdAt),
    index('_sources_v_updated_at_idx').on(columns.updatedAt),
    index('_sources_v_latest_idx').on(columns.latest),
  ],
)

export const parties = pgTable(
  'parties',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    slug: varchar('slug'),
    shortName: varchar('short_name'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    color: varchar('color'),
    website: varchar('website'),
    description: varchar('description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_parties_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('parties_slug_idx').on(columns.slug),
    index('parties_logo_idx').on(columns.logo),
    index('parties_updated_at_idx').on(columns.updatedAt),
    index('parties_created_at_idx').on(columns.createdAt),
    index('parties__status_idx').on(columns._status),
  ],
)

export const parties_rels = pgTable(
  'parties_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    sourcesID: integer('sources_id'),
  },
  (columns) => [
    index('parties_rels_order_idx').on(columns.order),
    index('parties_rels_parent_idx').on(columns.parent),
    index('parties_rels_path_idx').on(columns.path),
    index('parties_rels_sources_id_idx').on(columns.sourcesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [parties.id],
      name: 'parties_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sourcesID']],
      foreignColumns: [sources.id],
      name: 'parties_rels_sources_fk',
    }).onDelete('cascade'),
  ],
)

export const _parties_v = pgTable(
  '_parties_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => parties.id, {
      onDelete: 'set null',
    }),
    version_name: varchar('version_name'),
    version_slug: varchar('version_slug'),
    version_shortName: varchar('version_short_name'),
    version_logo: integer('version_logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_color: varchar('version_color'),
    version_website: varchar('version_website'),
    version_description: varchar('version_description'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__parties_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_parties_v_parent_idx').on(columns.parent),
    index('_parties_v_version_version_slug_idx').on(columns.version_slug),
    index('_parties_v_version_version_logo_idx').on(columns.version_logo),
    index('_parties_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_parties_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_parties_v_version_version__status_idx').on(columns.version__status),
    index('_parties_v_created_at_idx').on(columns.createdAt),
    index('_parties_v_updated_at_idx').on(columns.updatedAt),
    index('_parties_v_latest_idx').on(columns.latest),
  ],
)

export const _parties_v_rels = pgTable(
  '_parties_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    sourcesID: integer('sources_id'),
  },
  (columns) => [
    index('_parties_v_rels_order_idx').on(columns.order),
    index('_parties_v_rels_parent_idx').on(columns.parent),
    index('_parties_v_rels_path_idx').on(columns.path),
    index('_parties_v_rels_sources_id_idx').on(columns.sourcesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_parties_v.id],
      name: '_parties_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sourcesID']],
      foreignColumns: [sources.id],
      name: '_parties_v_rels_sources_fk',
    }).onDelete('cascade'),
  ],
)

export const candidates = pgTable(
  'candidates',
  {
    id: serial('id').primaryKey(),
    firstName: varchar('first_name'),
    lastName: varchar('last_name'),
    displayName: varchar('display_name'),
    slug: varchar('slug'),
    photo: integer('photo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    currentParty: integer('current_party_id').references(() => parties.id, {
      onDelete: 'set null',
    }),
    candidacyStatus: enum_candidates_candidacy_status('candidacy_status').default('expected'),
    website: varchar('website'),
    bio: varchar('bio'),
    sortOrder: numeric('sort_order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_candidates_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('candidates_slug_idx').on(columns.slug),
    index('candidates_photo_idx').on(columns.photo),
    index('candidates_current_party_idx').on(columns.currentParty),
    index('candidates_sort_order_idx').on(columns.sortOrder),
    index('candidates_updated_at_idx').on(columns.updatedAt),
    index('candidates_created_at_idx').on(columns.createdAt),
    index('candidates__status_idx').on(columns._status),
  ],
)

export const candidates_rels = pgTable(
  'candidates_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    sourcesID: integer('sources_id'),
  },
  (columns) => [
    index('candidates_rels_order_idx').on(columns.order),
    index('candidates_rels_parent_idx').on(columns.parent),
    index('candidates_rels_path_idx').on(columns.path),
    index('candidates_rels_sources_id_idx').on(columns.sourcesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [candidates.id],
      name: 'candidates_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sourcesID']],
      foreignColumns: [sources.id],
      name: 'candidates_rels_sources_fk',
    }).onDelete('cascade'),
  ],
)

export const _candidates_v = pgTable(
  '_candidates_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => candidates.id, {
      onDelete: 'set null',
    }),
    version_firstName: varchar('version_first_name'),
    version_lastName: varchar('version_last_name'),
    version_displayName: varchar('version_display_name'),
    version_slug: varchar('version_slug'),
    version_photo: integer('version_photo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_currentParty: integer('version_current_party_id').references(() => parties.id, {
      onDelete: 'set null',
    }),
    version_candidacyStatus: enum__candidates_v_version_candidacy_status(
      'version_candidacy_status',
    ).default('expected'),
    version_website: varchar('version_website'),
    version_bio: varchar('version_bio'),
    version_sortOrder: numeric('version_sort_order', { mode: 'number' }).default(0),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__candidates_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_candidates_v_parent_idx').on(columns.parent),
    index('_candidates_v_version_version_slug_idx').on(columns.version_slug),
    index('_candidates_v_version_version_photo_idx').on(columns.version_photo),
    index('_candidates_v_version_version_current_party_idx').on(columns.version_currentParty),
    index('_candidates_v_version_version_sort_order_idx').on(columns.version_sortOrder),
    index('_candidates_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_candidates_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_candidates_v_version_version__status_idx').on(columns.version__status),
    index('_candidates_v_created_at_idx').on(columns.createdAt),
    index('_candidates_v_updated_at_idx').on(columns.updatedAt),
    index('_candidates_v_latest_idx').on(columns.latest),
  ],
)

export const _candidates_v_rels = pgTable(
  '_candidates_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    sourcesID: integer('sources_id'),
  },
  (columns) => [
    index('_candidates_v_rels_order_idx').on(columns.order),
    index('_candidates_v_rels_parent_idx').on(columns.parent),
    index('_candidates_v_rels_path_idx').on(columns.path),
    index('_candidates_v_rels_sources_id_idx').on(columns.sourcesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_candidates_v.id],
      name: '_candidates_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sourcesID']],
      foreignColumns: [sources.id],
      name: '_candidates_v_rels_sources_fk',
    }).onDelete('cascade'),
  ],
)

export const topics = pgTable(
  'topics',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    description: varchar('description'),
    parent: integer('parent_id').references((): AnyPgColumn => topics.id, {
      onDelete: 'set null',
    }),
    order: numeric('order', { mode: 'number' }).default(0),
    color: varchar('color'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_topics_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('topics_slug_idx').on(columns.slug),
    index('topics_parent_idx').on(columns.parent),
    index('topics_order_idx').on(columns.order),
    index('topics_updated_at_idx').on(columns.updatedAt),
    index('topics_created_at_idx').on(columns.createdAt),
    index('topics__status_idx').on(columns._status),
  ],
)

export const _topics_v = pgTable(
  '_topics_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => topics.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_description: varchar('version_description'),
    version_parent: integer('version_parent_id').references(() => topics.id, {
      onDelete: 'set null',
    }),
    version_order: numeric('version_order', { mode: 'number' }).default(0),
    version_color: varchar('version_color'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__topics_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_topics_v_parent_idx').on(columns.parent),
    index('_topics_v_version_version_slug_idx').on(columns.version_slug),
    index('_topics_v_version_version_parent_idx').on(columns.version_parent),
    index('_topics_v_version_version_order_idx').on(columns.version_order),
    index('_topics_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_topics_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_topics_v_version_version__status_idx').on(columns.version__status),
    index('_topics_v_created_at_idx').on(columns.createdAt),
    index('_topics_v_updated_at_idx').on(columns.updatedAt),
    index('_topics_v_latest_idx').on(columns.latest),
  ],
)

export const programs = pgTable(
  'programs',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    source: integer('source_id').references(() => sources.id, {
      onDelete: 'set null',
    }),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    programDate: timestamp('program_date', { mode: 'string', withTimezone: true, precision: 3 }),
    summary: varchar('summary'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_programs_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('programs_slug_idx').on(columns.slug),
    index('programs_source_idx').on(columns.source),
    index('programs_file_idx').on(columns.file),
    index('programs_program_date_idx').on(columns.programDate),
    index('programs_updated_at_idx').on(columns.updatedAt),
    index('programs_created_at_idx').on(columns.createdAt),
    index('programs__status_idx').on(columns._status),
  ],
)

export const programs_rels = pgTable(
  'programs_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    candidatesID: integer('candidates_id'),
    partiesID: integer('parties_id'),
  },
  (columns) => [
    index('programs_rels_order_idx').on(columns.order),
    index('programs_rels_parent_idx').on(columns.parent),
    index('programs_rels_path_idx').on(columns.path),
    index('programs_rels_candidates_id_idx').on(columns.candidatesID),
    index('programs_rels_parties_id_idx').on(columns.partiesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [programs.id],
      name: 'programs_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['candidatesID']],
      foreignColumns: [candidates.id],
      name: 'programs_rels_candidates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partiesID']],
      foreignColumns: [parties.id],
      name: 'programs_rels_parties_fk',
    }).onDelete('cascade'),
  ],
)

export const _programs_v = pgTable(
  '_programs_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => programs.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_source: integer('version_source_id').references(() => sources.id, {
      onDelete: 'set null',
    }),
    version_file: integer('version_file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_programDate: timestamp('version_program_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_summary: varchar('version_summary'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__programs_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_programs_v_parent_idx').on(columns.parent),
    index('_programs_v_version_version_slug_idx').on(columns.version_slug),
    index('_programs_v_version_version_source_idx').on(columns.version_source),
    index('_programs_v_version_version_file_idx').on(columns.version_file),
    index('_programs_v_version_version_program_date_idx').on(columns.version_programDate),
    index('_programs_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_programs_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_programs_v_version_version__status_idx').on(columns.version__status),
    index('_programs_v_created_at_idx').on(columns.createdAt),
    index('_programs_v_updated_at_idx').on(columns.updatedAt),
    index('_programs_v_latest_idx').on(columns.latest),
  ],
)

export const _programs_v_rels = pgTable(
  '_programs_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    candidatesID: integer('candidates_id'),
    partiesID: integer('parties_id'),
  },
  (columns) => [
    index('_programs_v_rels_order_idx').on(columns.order),
    index('_programs_v_rels_parent_idx').on(columns.parent),
    index('_programs_v_rels_path_idx').on(columns.path),
    index('_programs_v_rels_candidates_id_idx').on(columns.candidatesID),
    index('_programs_v_rels_parties_id_idx').on(columns.partiesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_programs_v.id],
      name: '_programs_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['candidatesID']],
      foreignColumns: [candidates.id],
      name: '_programs_v_rels_candidates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partiesID']],
      foreignColumns: [parties.id],
      name: '_programs_v_rels_parties_fk',
    }).onDelete('cascade'),
  ],
)

export const proposals = pgTable(
  'proposals',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    summary: varchar('summary'),
    details: varchar('details'),
    proposalStatus: enum_proposals_proposal_status('proposal_status').default('announced'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    lastVerifiedAt: timestamp('last_verified_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_proposals_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('proposals_slug_idx').on(columns.slug),
    index('proposals_published_at_idx').on(columns.publishedAt),
    index('proposals_updated_at_idx').on(columns.updatedAt),
    index('proposals_created_at_idx').on(columns.createdAt),
    index('proposals__status_idx').on(columns._status),
  ],
)

export const proposals_rels = pgTable(
  'proposals_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    candidatesID: integer('candidates_id'),
    partiesID: integer('parties_id'),
    topicsID: integer('topics_id'),
    sourcesID: integer('sources_id'),
  },
  (columns) => [
    index('proposals_rels_order_idx').on(columns.order),
    index('proposals_rels_parent_idx').on(columns.parent),
    index('proposals_rels_path_idx').on(columns.path),
    index('proposals_rels_candidates_id_idx').on(columns.candidatesID),
    index('proposals_rels_parties_id_idx').on(columns.partiesID),
    index('proposals_rels_topics_id_idx').on(columns.topicsID),
    index('proposals_rels_sources_id_idx').on(columns.sourcesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [proposals.id],
      name: 'proposals_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['candidatesID']],
      foreignColumns: [candidates.id],
      name: 'proposals_rels_candidates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partiesID']],
      foreignColumns: [parties.id],
      name: 'proposals_rels_parties_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['topicsID']],
      foreignColumns: [topics.id],
      name: 'proposals_rels_topics_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sourcesID']],
      foreignColumns: [sources.id],
      name: 'proposals_rels_sources_fk',
    }).onDelete('cascade'),
  ],
)

export const _proposals_v = pgTable(
  '_proposals_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => proposals.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_summary: varchar('version_summary'),
    version_details: varchar('version_details'),
    version_proposalStatus:
      enum__proposals_v_version_proposal_status('version_proposal_status').default('announced'),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_lastVerifiedAt: timestamp('version_last_verified_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__proposals_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_proposals_v_parent_idx').on(columns.parent),
    index('_proposals_v_version_version_slug_idx').on(columns.version_slug),
    index('_proposals_v_version_version_published_at_idx').on(columns.version_publishedAt),
    index('_proposals_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_proposals_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_proposals_v_version_version__status_idx').on(columns.version__status),
    index('_proposals_v_created_at_idx').on(columns.createdAt),
    index('_proposals_v_updated_at_idx').on(columns.updatedAt),
    index('_proposals_v_latest_idx').on(columns.latest),
  ],
)

export const _proposals_v_rels = pgTable(
  '_proposals_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    candidatesID: integer('candidates_id'),
    partiesID: integer('parties_id'),
    topicsID: integer('topics_id'),
    sourcesID: integer('sources_id'),
  },
  (columns) => [
    index('_proposals_v_rels_order_idx').on(columns.order),
    index('_proposals_v_rels_parent_idx').on(columns.parent),
    index('_proposals_v_rels_path_idx').on(columns.path),
    index('_proposals_v_rels_candidates_id_idx').on(columns.candidatesID),
    index('_proposals_v_rels_parties_id_idx').on(columns.partiesID),
    index('_proposals_v_rels_topics_id_idx').on(columns.topicsID),
    index('_proposals_v_rels_sources_id_idx').on(columns.sourcesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_proposals_v.id],
      name: '_proposals_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['candidatesID']],
      foreignColumns: [candidates.id],
      name: '_proposals_v_rels_candidates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partiesID']],
      foreignColumns: [parties.id],
      name: '_proposals_v_rels_parties_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['topicsID']],
      foreignColumns: [topics.id],
      name: '_proposals_v_rels_topics_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sourcesID']],
      foreignColumns: [sources.id],
      name: '_proposals_v_rels_sources_fk',
    }).onDelete('cascade'),
  ],
)

export const public_positions = pgTable(
  'public_positions',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    source: integer('source_id').references(() => sources.id, {
      onDelete: 'set null',
    }),
    positionDate: timestamp('position_date', { mode: 'string', withTimezone: true, precision: 3 }),
    positionType: enum_public_positions_position_type('position_type').default('other'),
    quote: varchar('quote'),
    summary: varchar('summary'),
    stance: enum_public_positions_stance('stance').default('unclear'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_public_positions_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('public_positions_slug_idx').on(columns.slug),
    index('public_positions_source_idx').on(columns.source),
    index('public_positions_position_date_idx').on(columns.positionDate),
    index('public_positions_updated_at_idx').on(columns.updatedAt),
    index('public_positions_created_at_idx').on(columns.createdAt),
    index('public_positions__status_idx').on(columns._status),
  ],
)

export const public_positions_rels = pgTable(
  'public_positions_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    candidatesID: integer('candidates_id'),
    partiesID: integer('parties_id'),
    topicsID: integer('topics_id'),
  },
  (columns) => [
    index('public_positions_rels_order_idx').on(columns.order),
    index('public_positions_rels_parent_idx').on(columns.parent),
    index('public_positions_rels_path_idx').on(columns.path),
    index('public_positions_rels_candidates_id_idx').on(columns.candidatesID),
    index('public_positions_rels_parties_id_idx').on(columns.partiesID),
    index('public_positions_rels_topics_id_idx').on(columns.topicsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [public_positions.id],
      name: 'public_positions_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['candidatesID']],
      foreignColumns: [candidates.id],
      name: 'public_positions_rels_candidates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partiesID']],
      foreignColumns: [parties.id],
      name: 'public_positions_rels_parties_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['topicsID']],
      foreignColumns: [topics.id],
      name: 'public_positions_rels_topics_fk',
    }).onDelete('cascade'),
  ],
)

export const _public_positions_v = pgTable(
  '_public_positions_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => public_positions.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_source: integer('version_source_id').references(() => sources.id, {
      onDelete: 'set null',
    }),
    version_positionDate: timestamp('version_position_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_positionType:
      enum__public_positions_v_version_position_type('version_position_type').default('other'),
    version_quote: varchar('version_quote'),
    version_summary: varchar('version_summary'),
    version_stance: enum__public_positions_v_version_stance('version_stance').default('unclear'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__public_positions_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_public_positions_v_parent_idx').on(columns.parent),
    index('_public_positions_v_version_version_slug_idx').on(columns.version_slug),
    index('_public_positions_v_version_version_source_idx').on(columns.version_source),
    index('_public_positions_v_version_version_position_date_idx').on(columns.version_positionDate),
    index('_public_positions_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_public_positions_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_public_positions_v_version_version__status_idx').on(columns.version__status),
    index('_public_positions_v_created_at_idx').on(columns.createdAt),
    index('_public_positions_v_updated_at_idx').on(columns.updatedAt),
    index('_public_positions_v_latest_idx').on(columns.latest),
  ],
)

export const _public_positions_v_rels = pgTable(
  '_public_positions_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    candidatesID: integer('candidates_id'),
    partiesID: integer('parties_id'),
    topicsID: integer('topics_id'),
  },
  (columns) => [
    index('_public_positions_v_rels_order_idx').on(columns.order),
    index('_public_positions_v_rels_parent_idx').on(columns.parent),
    index('_public_positions_v_rels_path_idx').on(columns.path),
    index('_public_positions_v_rels_candidates_id_idx').on(columns.candidatesID),
    index('_public_positions_v_rels_parties_id_idx').on(columns.partiesID),
    index('_public_positions_v_rels_topics_id_idx').on(columns.topicsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_public_positions_v.id],
      name: '_public_positions_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['candidatesID']],
      foreignColumns: [candidates.id],
      name: '_public_positions_v_rels_candidates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partiesID']],
      foreignColumns: [parties.id],
      name: '_public_positions_v_rels_parties_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['topicsID']],
      foreignColumns: [topics.id],
      name: '_public_positions_v_rels_topics_fk',
    }).onDelete('cascade'),
  ],
)

export const search = pgTable(
  'search',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    priority: numeric('priority', { mode: 'number' }),
    collectionSlug: varchar('collection_slug'),
    excerpt: varchar('excerpt'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('search_collection_slug_idx').on(columns.collectionSlug),
    index('search_updated_at_idx').on(columns.updatedAt),
    index('search_created_at_idx').on(columns.createdAt),
  ],
)

export const search_rels = pgTable(
  'search_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    partiesID: integer('parties_id'),
    candidatesID: integer('candidates_id'),
    topicsID: integer('topics_id'),
    programsID: integer('programs_id'),
    proposalsID: integer('proposals_id'),
    'public-positionsID': integer('public_positions_id'),
  },
  (columns) => [
    index('search_rels_order_idx').on(columns.order),
    index('search_rels_parent_idx').on(columns.parent),
    index('search_rels_path_idx').on(columns.path),
    index('search_rels_parties_id_idx').on(columns.partiesID),
    index('search_rels_candidates_id_idx').on(columns.candidatesID),
    index('search_rels_topics_id_idx').on(columns.topicsID),
    index('search_rels_programs_id_idx').on(columns.programsID),
    index('search_rels_proposals_id_idx').on(columns.proposalsID),
    index('search_rels_public_positions_id_idx').on(columns['public-positionsID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [search.id],
      name: 'search_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partiesID']],
      foreignColumns: [parties.id],
      name: 'search_rels_parties_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['candidatesID']],
      foreignColumns: [candidates.id],
      name: 'search_rels_candidates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['topicsID']],
      foreignColumns: [topics.id],
      name: 'search_rels_topics_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'search_rels_programs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['proposalsID']],
      foreignColumns: [proposals.id],
      name: 'search_rels_proposals_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['public-positionsID']],
      foreignColumns: [public_positions.id],
      name: 'search_rels_public_positions_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    sessionsID: integer('sessions_id'),
    accountsID: integer('accounts_id'),
    verificationsID: integer('verifications_id'),
    twoFactorsID: integer('two_factors_id'),
    'admin-invitationsID': integer('admin_invitations_id'),
    mediaID: integer('media_id'),
    sourcesID: integer('sources_id'),
    partiesID: integer('parties_id'),
    candidatesID: integer('candidates_id'),
    topicsID: integer('topics_id'),
    programsID: integer('programs_id'),
    proposalsID: integer('proposals_id'),
    'public-positionsID': integer('public_positions_id'),
    searchID: integer('search_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_sessions_id_idx').on(columns.sessionsID),
    index('payload_locked_documents_rels_accounts_id_idx').on(columns.accountsID),
    index('payload_locked_documents_rels_verifications_id_idx').on(columns.verificationsID),
    index('payload_locked_documents_rels_two_factors_id_idx').on(columns.twoFactorsID),
    index('payload_locked_documents_rels_admin_invitations_id_idx').on(
      columns['admin-invitationsID'],
    ),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_sources_id_idx').on(columns.sourcesID),
    index('payload_locked_documents_rels_parties_id_idx').on(columns.partiesID),
    index('payload_locked_documents_rels_candidates_id_idx').on(columns.candidatesID),
    index('payload_locked_documents_rels_topics_id_idx').on(columns.topicsID),
    index('payload_locked_documents_rels_programs_id_idx').on(columns.programsID),
    index('payload_locked_documents_rels_proposals_id_idx').on(columns.proposalsID),
    index('payload_locked_documents_rels_public_positions_id_idx').on(
      columns['public-positionsID'],
    ),
    index('payload_locked_documents_rels_search_id_idx').on(columns.searchID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sessionsID']],
      foreignColumns: [sessions.id],
      name: 'payload_locked_documents_rels_sessions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['accountsID']],
      foreignColumns: [accounts.id],
      name: 'payload_locked_documents_rels_accounts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['verificationsID']],
      foreignColumns: [verifications.id],
      name: 'payload_locked_documents_rels_verifications_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['twoFactorsID']],
      foreignColumns: [two_factors.id],
      name: 'payload_locked_documents_rels_two_factors_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['admin-invitationsID']],
      foreignColumns: [admin_invitations.id],
      name: 'payload_locked_documents_rels_admin_invitations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['sourcesID']],
      foreignColumns: [sources.id],
      name: 'payload_locked_documents_rels_sources_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partiesID']],
      foreignColumns: [parties.id],
      name: 'payload_locked_documents_rels_parties_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['candidatesID']],
      foreignColumns: [candidates.id],
      name: 'payload_locked_documents_rels_candidates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['topicsID']],
      foreignColumns: [topics.id],
      name: 'payload_locked_documents_rels_topics_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'payload_locked_documents_rels_programs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['proposalsID']],
      foreignColumns: [proposals.id],
      name: 'payload_locked_documents_rels_proposals_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['public-positionsID']],
      foreignColumns: [public_positions.id],
      name: 'payload_locked_documents_rels_public_positions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['searchID']],
      foreignColumns: [search.id],
      name: 'payload_locked_documents_rels_search_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const database = pgTable('database', {
  id: serial('id').primaryKey(),
  seeded: boolean('seeded').notNull().default(false),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_users_role = relations(users_role, ({ one }) => ({
  parent: one(users, {
    fields: [users_role.parent],
    references: [users.id],
    relationName: 'role',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  role: many(users_role, {
    relationName: 'role',
  }),
}))
export const relations_sessions = relations(sessions, ({ one }) => ({
  user: one(users, {
    fields: [sessions.user],
    references: [users.id],
    relationName: 'user',
  }),
  impersonatedBy: one(users, {
    fields: [sessions.impersonatedBy],
    references: [users.id],
    relationName: 'impersonatedBy',
  }),
}))
export const relations_accounts = relations(accounts, ({ one }) => ({
  user: one(users, {
    fields: [accounts.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_verifications = relations(verifications, () => ({}))
export const relations_two_factors = relations(two_factors, ({ one }) => ({
  user: one(users, {
    fields: [two_factors.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_admin_invitations = relations(admin_invitations, () => ({}))
export const relations_media = relations(media, () => ({}))
export const relations_sources = relations(sources, ({ one }) => ({
  file: one(media, {
    fields: [sources.file],
    references: [media.id],
    relationName: 'file',
  }),
}))
export const relations__sources_v = relations(_sources_v, ({ one }) => ({
  parent: one(sources, {
    fields: [_sources_v.parent],
    references: [sources.id],
    relationName: 'parent',
  }),
  version_file: one(media, {
    fields: [_sources_v.version_file],
    references: [media.id],
    relationName: 'version_file',
  }),
}))
export const relations_parties_rels = relations(parties_rels, ({ one }) => ({
  parent: one(parties, {
    fields: [parties_rels.parent],
    references: [parties.id],
    relationName: '_rels',
  }),
  sourcesID: one(sources, {
    fields: [parties_rels.sourcesID],
    references: [sources.id],
    relationName: 'sources',
  }),
}))
export const relations_parties = relations(parties, ({ one, many }) => ({
  logo: one(media, {
    fields: [parties.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  _rels: many(parties_rels, {
    relationName: '_rels',
  }),
}))
export const relations__parties_v_rels = relations(_parties_v_rels, ({ one }) => ({
  parent: one(_parties_v, {
    fields: [_parties_v_rels.parent],
    references: [_parties_v.id],
    relationName: '_rels',
  }),
  sourcesID: one(sources, {
    fields: [_parties_v_rels.sourcesID],
    references: [sources.id],
    relationName: 'sources',
  }),
}))
export const relations__parties_v = relations(_parties_v, ({ one, many }) => ({
  parent: one(parties, {
    fields: [_parties_v.parent],
    references: [parties.id],
    relationName: 'parent',
  }),
  version_logo: one(media, {
    fields: [_parties_v.version_logo],
    references: [media.id],
    relationName: 'version_logo',
  }),
  _rels: many(_parties_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_candidates_rels = relations(candidates_rels, ({ one }) => ({
  parent: one(candidates, {
    fields: [candidates_rels.parent],
    references: [candidates.id],
    relationName: '_rels',
  }),
  sourcesID: one(sources, {
    fields: [candidates_rels.sourcesID],
    references: [sources.id],
    relationName: 'sources',
  }),
}))
export const relations_candidates = relations(candidates, ({ one, many }) => ({
  photo: one(media, {
    fields: [candidates.photo],
    references: [media.id],
    relationName: 'photo',
  }),
  currentParty: one(parties, {
    fields: [candidates.currentParty],
    references: [parties.id],
    relationName: 'currentParty',
  }),
  _rels: many(candidates_rels, {
    relationName: '_rels',
  }),
}))
export const relations__candidates_v_rels = relations(_candidates_v_rels, ({ one }) => ({
  parent: one(_candidates_v, {
    fields: [_candidates_v_rels.parent],
    references: [_candidates_v.id],
    relationName: '_rels',
  }),
  sourcesID: one(sources, {
    fields: [_candidates_v_rels.sourcesID],
    references: [sources.id],
    relationName: 'sources',
  }),
}))
export const relations__candidates_v = relations(_candidates_v, ({ one, many }) => ({
  parent: one(candidates, {
    fields: [_candidates_v.parent],
    references: [candidates.id],
    relationName: 'parent',
  }),
  version_photo: one(media, {
    fields: [_candidates_v.version_photo],
    references: [media.id],
    relationName: 'version_photo',
  }),
  version_currentParty: one(parties, {
    fields: [_candidates_v.version_currentParty],
    references: [parties.id],
    relationName: 'version_currentParty',
  }),
  _rels: many(_candidates_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_topics = relations(topics, ({ one }) => ({
  parent: one(topics, {
    fields: [topics.parent],
    references: [topics.id],
    relationName: 'parent',
  }),
}))
export const relations__topics_v = relations(_topics_v, ({ one }) => ({
  parent: one(topics, {
    fields: [_topics_v.parent],
    references: [topics.id],
    relationName: 'parent',
  }),
  version_parent: one(topics, {
    fields: [_topics_v.version_parent],
    references: [topics.id],
    relationName: 'version_parent',
  }),
}))
export const relations_programs_rels = relations(programs_rels, ({ one }) => ({
  parent: one(programs, {
    fields: [programs_rels.parent],
    references: [programs.id],
    relationName: '_rels',
  }),
  candidatesID: one(candidates, {
    fields: [programs_rels.candidatesID],
    references: [candidates.id],
    relationName: 'candidates',
  }),
  partiesID: one(parties, {
    fields: [programs_rels.partiesID],
    references: [parties.id],
    relationName: 'parties',
  }),
}))
export const relations_programs = relations(programs, ({ one, many }) => ({
  source: one(sources, {
    fields: [programs.source],
    references: [sources.id],
    relationName: 'source',
  }),
  file: one(media, {
    fields: [programs.file],
    references: [media.id],
    relationName: 'file',
  }),
  _rels: many(programs_rels, {
    relationName: '_rels',
  }),
}))
export const relations__programs_v_rels = relations(_programs_v_rels, ({ one }) => ({
  parent: one(_programs_v, {
    fields: [_programs_v_rels.parent],
    references: [_programs_v.id],
    relationName: '_rels',
  }),
  candidatesID: one(candidates, {
    fields: [_programs_v_rels.candidatesID],
    references: [candidates.id],
    relationName: 'candidates',
  }),
  partiesID: one(parties, {
    fields: [_programs_v_rels.partiesID],
    references: [parties.id],
    relationName: 'parties',
  }),
}))
export const relations__programs_v = relations(_programs_v, ({ one, many }) => ({
  parent: one(programs, {
    fields: [_programs_v.parent],
    references: [programs.id],
    relationName: 'parent',
  }),
  version_source: one(sources, {
    fields: [_programs_v.version_source],
    references: [sources.id],
    relationName: 'version_source',
  }),
  version_file: one(media, {
    fields: [_programs_v.version_file],
    references: [media.id],
    relationName: 'version_file',
  }),
  _rels: many(_programs_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_proposals_rels = relations(proposals_rels, ({ one }) => ({
  parent: one(proposals, {
    fields: [proposals_rels.parent],
    references: [proposals.id],
    relationName: '_rels',
  }),
  candidatesID: one(candidates, {
    fields: [proposals_rels.candidatesID],
    references: [candidates.id],
    relationName: 'candidates',
  }),
  partiesID: one(parties, {
    fields: [proposals_rels.partiesID],
    references: [parties.id],
    relationName: 'parties',
  }),
  topicsID: one(topics, {
    fields: [proposals_rels.topicsID],
    references: [topics.id],
    relationName: 'topics',
  }),
  sourcesID: one(sources, {
    fields: [proposals_rels.sourcesID],
    references: [sources.id],
    relationName: 'sources',
  }),
}))
export const relations_proposals = relations(proposals, ({ many }) => ({
  _rels: many(proposals_rels, {
    relationName: '_rels',
  }),
}))
export const relations__proposals_v_rels = relations(_proposals_v_rels, ({ one }) => ({
  parent: one(_proposals_v, {
    fields: [_proposals_v_rels.parent],
    references: [_proposals_v.id],
    relationName: '_rels',
  }),
  candidatesID: one(candidates, {
    fields: [_proposals_v_rels.candidatesID],
    references: [candidates.id],
    relationName: 'candidates',
  }),
  partiesID: one(parties, {
    fields: [_proposals_v_rels.partiesID],
    references: [parties.id],
    relationName: 'parties',
  }),
  topicsID: one(topics, {
    fields: [_proposals_v_rels.topicsID],
    references: [topics.id],
    relationName: 'topics',
  }),
  sourcesID: one(sources, {
    fields: [_proposals_v_rels.sourcesID],
    references: [sources.id],
    relationName: 'sources',
  }),
}))
export const relations__proposals_v = relations(_proposals_v, ({ one, many }) => ({
  parent: one(proposals, {
    fields: [_proposals_v.parent],
    references: [proposals.id],
    relationName: 'parent',
  }),
  _rels: many(_proposals_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_public_positions_rels = relations(public_positions_rels, ({ one }) => ({
  parent: one(public_positions, {
    fields: [public_positions_rels.parent],
    references: [public_positions.id],
    relationName: '_rels',
  }),
  candidatesID: one(candidates, {
    fields: [public_positions_rels.candidatesID],
    references: [candidates.id],
    relationName: 'candidates',
  }),
  partiesID: one(parties, {
    fields: [public_positions_rels.partiesID],
    references: [parties.id],
    relationName: 'parties',
  }),
  topicsID: one(topics, {
    fields: [public_positions_rels.topicsID],
    references: [topics.id],
    relationName: 'topics',
  }),
}))
export const relations_public_positions = relations(public_positions, ({ one, many }) => ({
  source: one(sources, {
    fields: [public_positions.source],
    references: [sources.id],
    relationName: 'source',
  }),
  _rels: many(public_positions_rels, {
    relationName: '_rels',
  }),
}))
export const relations__public_positions_v_rels = relations(
  _public_positions_v_rels,
  ({ one }) => ({
    parent: one(_public_positions_v, {
      fields: [_public_positions_v_rels.parent],
      references: [_public_positions_v.id],
      relationName: '_rels',
    }),
    candidatesID: one(candidates, {
      fields: [_public_positions_v_rels.candidatesID],
      references: [candidates.id],
      relationName: 'candidates',
    }),
    partiesID: one(parties, {
      fields: [_public_positions_v_rels.partiesID],
      references: [parties.id],
      relationName: 'parties',
    }),
    topicsID: one(topics, {
      fields: [_public_positions_v_rels.topicsID],
      references: [topics.id],
      relationName: 'topics',
    }),
  }),
)
export const relations__public_positions_v = relations(_public_positions_v, ({ one, many }) => ({
  parent: one(public_positions, {
    fields: [_public_positions_v.parent],
    references: [public_positions.id],
    relationName: 'parent',
  }),
  version_source: one(sources, {
    fields: [_public_positions_v.version_source],
    references: [sources.id],
    relationName: 'version_source',
  }),
  _rels: many(_public_positions_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_search_rels = relations(search_rels, ({ one }) => ({
  parent: one(search, {
    fields: [search_rels.parent],
    references: [search.id],
    relationName: '_rels',
  }),
  partiesID: one(parties, {
    fields: [search_rels.partiesID],
    references: [parties.id],
    relationName: 'parties',
  }),
  candidatesID: one(candidates, {
    fields: [search_rels.candidatesID],
    references: [candidates.id],
    relationName: 'candidates',
  }),
  topicsID: one(topics, {
    fields: [search_rels.topicsID],
    references: [topics.id],
    relationName: 'topics',
  }),
  programsID: one(programs, {
    fields: [search_rels.programsID],
    references: [programs.id],
    relationName: 'programs',
  }),
  proposalsID: one(proposals, {
    fields: [search_rels.proposalsID],
    references: [proposals.id],
    relationName: 'proposals',
  }),
  'public-positionsID': one(public_positions, {
    fields: [search_rels['public-positionsID']],
    references: [public_positions.id],
    relationName: 'public-positions',
  }),
}))
export const relations_search = relations(search, ({ many }) => ({
  _rels: many(search_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    sessionsID: one(sessions, {
      fields: [payload_locked_documents_rels.sessionsID],
      references: [sessions.id],
      relationName: 'sessions',
    }),
    accountsID: one(accounts, {
      fields: [payload_locked_documents_rels.accountsID],
      references: [accounts.id],
      relationName: 'accounts',
    }),
    verificationsID: one(verifications, {
      fields: [payload_locked_documents_rels.verificationsID],
      references: [verifications.id],
      relationName: 'verifications',
    }),
    twoFactorsID: one(two_factors, {
      fields: [payload_locked_documents_rels.twoFactorsID],
      references: [two_factors.id],
      relationName: 'twoFactors',
    }),
    'admin-invitationsID': one(admin_invitations, {
      fields: [payload_locked_documents_rels['admin-invitationsID']],
      references: [admin_invitations.id],
      relationName: 'admin-invitations',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    sourcesID: one(sources, {
      fields: [payload_locked_documents_rels.sourcesID],
      references: [sources.id],
      relationName: 'sources',
    }),
    partiesID: one(parties, {
      fields: [payload_locked_documents_rels.partiesID],
      references: [parties.id],
      relationName: 'parties',
    }),
    candidatesID: one(candidates, {
      fields: [payload_locked_documents_rels.candidatesID],
      references: [candidates.id],
      relationName: 'candidates',
    }),
    topicsID: one(topics, {
      fields: [payload_locked_documents_rels.topicsID],
      references: [topics.id],
      relationName: 'topics',
    }),
    programsID: one(programs, {
      fields: [payload_locked_documents_rels.programsID],
      references: [programs.id],
      relationName: 'programs',
    }),
    proposalsID: one(proposals, {
      fields: [payload_locked_documents_rels.proposalsID],
      references: [proposals.id],
      relationName: 'proposals',
    }),
    'public-positionsID': one(public_positions, {
      fields: [payload_locked_documents_rels['public-positionsID']],
      references: [public_positions.id],
      relationName: 'public-positions',
    }),
    searchID: one(search, {
      fields: [payload_locked_documents_rels.searchID],
      references: [search.id],
      relationName: 'search',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_database = relations(database, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_admin_invitations_role: typeof enum_admin_invitations_role
  enum_sources_type: typeof enum_sources_type
  enum_sources_verification_status: typeof enum_sources_verification_status
  enum_sources_status: typeof enum_sources_status
  enum__sources_v_version_type: typeof enum__sources_v_version_type
  enum__sources_v_version_verification_status: typeof enum__sources_v_version_verification_status
  enum__sources_v_version_status: typeof enum__sources_v_version_status
  enum_parties_status: typeof enum_parties_status
  enum__parties_v_version_status: typeof enum__parties_v_version_status
  enum_candidates_candidacy_status: typeof enum_candidates_candidacy_status
  enum_candidates_status: typeof enum_candidates_status
  enum__candidates_v_version_candidacy_status: typeof enum__candidates_v_version_candidacy_status
  enum__candidates_v_version_status: typeof enum__candidates_v_version_status
  enum_topics_status: typeof enum_topics_status
  enum__topics_v_version_status: typeof enum__topics_v_version_status
  enum_programs_status: typeof enum_programs_status
  enum__programs_v_version_status: typeof enum__programs_v_version_status
  enum_proposals_proposal_status: typeof enum_proposals_proposal_status
  enum_proposals_status: typeof enum_proposals_status
  enum__proposals_v_version_proposal_status: typeof enum__proposals_v_version_proposal_status
  enum__proposals_v_version_status: typeof enum__proposals_v_version_status
  enum_public_positions_position_type: typeof enum_public_positions_position_type
  enum_public_positions_stance: typeof enum_public_positions_stance
  enum_public_positions_status: typeof enum_public_positions_status
  enum__public_positions_v_version_position_type: typeof enum__public_positions_v_version_position_type
  enum__public_positions_v_version_stance: typeof enum__public_positions_v_version_stance
  enum__public_positions_v_version_status: typeof enum__public_positions_v_version_status
  users_role: typeof users_role
  users: typeof users
  sessions: typeof sessions
  accounts: typeof accounts
  verifications: typeof verifications
  two_factors: typeof two_factors
  admin_invitations: typeof admin_invitations
  media: typeof media
  sources: typeof sources
  _sources_v: typeof _sources_v
  parties: typeof parties
  parties_rels: typeof parties_rels
  _parties_v: typeof _parties_v
  _parties_v_rels: typeof _parties_v_rels
  candidates: typeof candidates
  candidates_rels: typeof candidates_rels
  _candidates_v: typeof _candidates_v
  _candidates_v_rels: typeof _candidates_v_rels
  topics: typeof topics
  _topics_v: typeof _topics_v
  programs: typeof programs
  programs_rels: typeof programs_rels
  _programs_v: typeof _programs_v
  _programs_v_rels: typeof _programs_v_rels
  proposals: typeof proposals
  proposals_rels: typeof proposals_rels
  _proposals_v: typeof _proposals_v
  _proposals_v_rels: typeof _proposals_v_rels
  public_positions: typeof public_positions
  public_positions_rels: typeof public_positions_rels
  _public_positions_v: typeof _public_positions_v
  _public_positions_v_rels: typeof _public_positions_v_rels
  search: typeof search
  search_rels: typeof search_rels
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  database: typeof database
  relations_users_role: typeof relations_users_role
  relations_users: typeof relations_users
  relations_sessions: typeof relations_sessions
  relations_accounts: typeof relations_accounts
  relations_verifications: typeof relations_verifications
  relations_two_factors: typeof relations_two_factors
  relations_admin_invitations: typeof relations_admin_invitations
  relations_media: typeof relations_media
  relations_sources: typeof relations_sources
  relations__sources_v: typeof relations__sources_v
  relations_parties_rels: typeof relations_parties_rels
  relations_parties: typeof relations_parties
  relations__parties_v_rels: typeof relations__parties_v_rels
  relations__parties_v: typeof relations__parties_v
  relations_candidates_rels: typeof relations_candidates_rels
  relations_candidates: typeof relations_candidates
  relations__candidates_v_rels: typeof relations__candidates_v_rels
  relations__candidates_v: typeof relations__candidates_v
  relations_topics: typeof relations_topics
  relations__topics_v: typeof relations__topics_v
  relations_programs_rels: typeof relations_programs_rels
  relations_programs: typeof relations_programs
  relations__programs_v_rels: typeof relations__programs_v_rels
  relations__programs_v: typeof relations__programs_v
  relations_proposals_rels: typeof relations_proposals_rels
  relations_proposals: typeof relations_proposals
  relations__proposals_v_rels: typeof relations__proposals_v_rels
  relations__proposals_v: typeof relations__proposals_v
  relations_public_positions_rels: typeof relations_public_positions_rels
  relations_public_positions: typeof relations_public_positions
  relations__public_positions_v_rels: typeof relations__public_positions_v_rels
  relations__public_positions_v: typeof relations__public_positions_v
  relations_search_rels: typeof relations_search_rels
  relations_search: typeof relations_search
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_database: typeof relations_database
}

declare module '@payloadcms/db-vercel-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
